include:
  - board: seeeduino_xiao_ble
    shield: lalapadmini_right
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: lalapadmini_left
  - board: seeeduino_xiao_ble
    shield: settings_reset